// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace e_drive_api.Migrations
{
    [DbContext(typeof(EdriveDb))]
    [Migration("20241214074333_companyinfo")]
    partial class companyinfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("t_company_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address_1")
                        .HasColumnType("text");

                    b.Property<string>("address_2")
                        .HasColumnType("text");

                    b.Property<string>("area_code")
                        .HasColumnType("text");

                    b.Property<string>("bussiness_name")
                        .HasColumnType("text");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("create_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("fax")
                        .HasColumnType("text");

                    b.Property<string>("phone_1")
                        .HasColumnType("text");

                    b.Property<string>("phone_2")
                        .HasColumnType("text");

                    b.Property<string>("postal_code")
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .HasColumnType("text");

                    b.Property<string>("update_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("website_url")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("t_company_info", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
